repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    - id: autoflake
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3.10
